import React, { useState, useEffect, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import { io } from 'socket.io-client';
import { Mic, MicOff, Video, VideoOff, MonitorUp, PhoneOff, Users, MessageSquare, Hand, Copy, ArrowUpRight, ArrowRight, Plus, ShieldCheck, Radio, X, Send, Settings, Lock, Unlock, Circle, Square, Download, Pencil, BarChart3, NotebookPen, Maximize, Pin, Volume2, Check, Youtube, Zap, Sun, Moon } from 'lucide-react';
import { Mesh } from './rtc';
import { NotesSync } from './notes-sync';
import './style.css';
import './academy.css';
import BoardStudio from './BoardStudio';
import Attendance from './Attendance';
import './skymeet.css';

const PALETTES = [['ember','Red & black','Pink & white'],['grove','Green & purple','Light green & lavender'],['pulse','Red & blue','Dark coral & sky blue'],['sky','Navy blue & black','Baby blue & white']];
const storage={get:k=>{try{return (k.startsWith('host:')?localStorage:sessionStorage).getItem(k);}catch{return null;}},set:(k,v)=>{try{(k.startsWith('host:')?localStorage:sessionStorage).setItem(k,v);}catch{}}};
const savedRooms=()=>{try{const rows=JSON.parse(localStorage.getItem('academy-classrooms')||'[]');return Array.isArray(rows)?rows.filter(r=>r&&typeof r.code==='string'&&/^[a-f0-9]{6}-[a-f0-9]{6}-[a-f0-9]{6}$/.test(r.code)&&typeof r.title==='string'):[];}catch{return [];}};
function rememberRoom(room){try{localStorage.setItem('academy-classrooms',JSON.stringify([{code:room.code,title:room.title,permanent:room.permanent},...savedRooms().filter(r=>r.code!==room.code)].slice(0,100)));}catch{}}
function participantKey(){try{let value=localStorage.getItem('academy-participant-key');if(!value){value=crypto.randomUUID();localStorage.setItem('academy-participant-key',value);}return value;}catch{return crypto.randomUUID();}}
if(location.hash.startsWith('#host=')){const key=decodeURIComponent(location.hash.slice(6));const roomCode=location.pathname.split('/').pop();if(/^[a-zA-Z0-9_-]{20,128}$/.test(key)&&roomCode)storage.set('host:'+roomCode,key);history.replaceState({},'',location.pathname);}
function download(name, text, type = 'text/plain') { const url = URL.createObjectURL(text instanceof Blob ? text : new Blob([text], { type })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 10000); }
const parseCode = value => { try { return new URL(value).pathname.split('/').filter(Boolean).pop(); } catch { return value.trim().split('/').filter(Boolean).pop() || ''; } };
const initials = name => name.split(/\s+/).map(s => s[0]).slice(0, 2).join('').toUpperCase();
const csv = value => '"' + String(value).replace(/^[=+@\-\t\r]/, "'$&").replaceAll('"', '""') + '"';
const fmtTime = t => new Date(t).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
function Brand() { return <a className="brand" href="/" aria-label="SkyMeet home"><img src="/icon.svg" alt=""/><span>SkyMeet<span className="brand-sub">SPACE TO CONNECT</span></span></a>; }
function IconButton({ icon: Icon, label, active, danger, onClick, disabled, children }) { return <button type="button" title={label} aria-label={label} aria-pressed={active === undefined ? undefined : active} className={`icon-button ${active ? 'active' : ''} ${danger ? 'danger' : ''}`} onClick={onClick} disabled={disabled}><Icon size={20}/>{children}</button>; }
function VideoTile({ participant, camera, screen, self, connection, pinned, onPin }) {
  const video = useRef(null), audio = useRef(null), [blocked, setBlocked] = useState(false);
  const isScreen = participant.sharing && screen;
  const visible = !!isScreen || participant.camera;
  useEffect(() => { const v = video.current; if (!v) return; v.srcObject = isScreen ? screen : camera; v.play().then(() => setBlocked(false)).catch(() => setBlocked(true)); }, [camera, screen, isScreen, visible]);
  useEffect(() => { const a = audio.current; if (!a || self) return; a.srcObject = camera; a.play().catch(() => setBlocked(true)); }, [camera, self]);
  return <article className={`tile ${pinned ? 'pinned' : ''} ${participant.hand ? 'raised' : ''}`} data-testid="video-tile">
    <video ref={video} autoPlay playsInline muted={!isScreen || self} className={`${!visible ? 'hidden-video' : ''} ${self && !isScreen ? 'mirror' : ''}`}/>
    {!self && <audio ref={audio} autoPlay/>}
    {!visible && <div className="avatar">{initials(participant.name)}</div>}
    <div className="tile-top"><span>{participant.role !== 'guest' && <span className="role">{participant.role === 'host' ? 'HOST' : 'CO-HOST'}</span>}{participant.hand && <span className="hand-tag">✋</span>}{participant.recording && <span className="record-tag">● REC</span>}</span><IconButton icon={Pin} label={`Pin ${participant.name}`} active={pinned} onClick={onPin}/></div>
    <div className="tile-caption"><span>{participant.name}{self ? ' (you)' : ''}{isScreen ? ' · presenting' : ''}</span><span className="tile-status">{!self && <small>{connection || 'connecting'}</small>}{participant.mic ? <Mic size={15}/> : <MicOff size={15}/>}</span></div>
    {blocked && <button className="play-audio" onClick={() => { video.current?.play().catch(() => {}); audio.current?.play().catch(() => {}); setBlocked(false); }}>Tap to play media</button>}
  </article>;
}

function App() {
  const [permanent,setPermanent]=useState(false),[whiteboard,setWhiteboard]=useState({objects:[],revision:0,enabled:true}),[cursors,setCursors]=useState({}),[showBoard,setShowBoard]=useState(false),[attendanceLoader,setAttendanceLoader]=useState(null),[storageWarning,setStorageWarning]=useState('');
  const initialCode = location.pathname.startsWith('/meet/') ? parseCode(location.pathname) : '';
  const [view,setView] = useState(initialCode ? 'prejoin' : 'home'), [code,setCode] = useState(initialCode), [room,setRoom] = useState(null), [config,setConfig] = useState(null);
  const [name,setName] = useState(storage.get('displayName') || ''), [title,setTitle] = useState('Team meeting'), [password,setPassword] = useState(''), [hostKey,setHostKey] = useState(''), [joinCode,setJoinCode] = useState('');
  const [toast,setToast] = useState(''), [busy,setBusy] = useState(false), [fatal,setFatal] = useState(''), [local,setLocal] = useState(null), [mic,setMic] = useState(false), [camera,setCamera] = useState(false), [devices,setDevices] = useState([]), [audioDevice,setAudioDevice] = useState(''), [videoDevice,setVideoDevice] = useState('');
  const [meeting,setMeeting] = useState(null), [selfId,setSelfId] = useState(''), [remotes,setRemotes] = useState({}), [connections,setConnections] = useState({}), [waiting,setWaiting] = useState([]), [messages,setMessages] = useState([]), [message,setMessage] = useState(''), [panel,setPanel] = useState('people'), [screen,setScreen] = useState(null), [pinned,setPinned] = useState(''), [hand,setHand] = useState(false), [online,setOnline] = useState(true), [recording,setRecording] = useState(false), [board,setBoard] = useState([]), [notes,setNotes] = useState(''), [poll,setPoll] = useState(null), [pollQuestion,setPollQuestion] = useState(''), [pollChoices,setPollChoices] = useState('Yes\nNo'), [elapsed,setElapsed] = useState(0), [light,setLight] = useState(() => { try { return localStorage.getItem('skymeet-mode') === 'light'; } catch { return false; } });
  const [palettes,setPalettes] = useState(() => { try { return JSON.parse(localStorage.getItem('skymeet-palettes') || '{}') || {}; } catch { return {}; } });
  const mode = light ? 'light' : 'dark';
  const palette = PALETTES.some(p => p[0] === palettes[mode]) ? palettes[mode] : 'sky';
  const socketRef = useRef(null), meshRef = useRef(null), localRef = useRef(null), screenRef = useRef(null), recordRef = useRef(null), timerRef = useRef(null), previewRef = useRef(null), noteSync = useRef(null), notifyTimer = useRef(null), joinData = useRef(null);
  const notify = text => { setToast(text); clearTimeout(notifyTimer.current); notifyTimer.current = setTimeout(() => setToast(''), 6500); };
  const [noteState,setNoteState] = useState({status:'Saved',conflict:false,dirty:false,remoteText:''});
  if(!noteSync.current)noteSync.current=new NotesSync(send,state=>{setNotes(state.text);setNoteState(state);});
  const self = meeting?.participants.find(p => p.id === selfId);
  const host = self && self.role !== 'guest';
  async function request(path, data) { const res = await fetch(path, data ? { method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data) } : {}); const result = await res.json(); if (!res.ok) throw new Error(result.error || 'Request failed.'); return result; }
  function send(event, data = {}) { return new Promise((resolve,reject) => { if (!socketRef.current?.connected) return reject(new Error('Connection lost. Please wait for reconnection.')); socketRef.current.timeout(10000).emit(event,data,(err,res) => err ? reject(new Error('Server did not respond. Try again.')) : res?.ok ? resolve(res) : reject(new Error(res?.error || 'Action failed.'))); }); }
  function action(event,data) { return send(event,data).catch(e => notify(e.message)); }
  useEffect(() => { request('/api/config').then(c=>{setConfig(c);setPermanent(c.permanentRooms);}).catch(() => notify('Server is starting. Refresh in a minute.')); return () => { socketRef.current?.disconnect(); meshRef.current?.close(); localRef.current?.getTracks().forEach(t => t.stop()); screenRef.current?.getTracks().forEach(t => t.stop()); clearInterval(timerRef.current); noteSync.current?.cancel(); }; }, []);
  useEffect(() => { if (view === 'prejoin' && code) request(`/api/rooms/${encodeURIComponent(code)}`).then(r => { setRoom(r);if(storage.get('host:'+r.code))rememberRoom(r); setFatal(''); }).catch(e => setFatal(e.message)); }, [code,view]);
  useEffect(()=>{if(view!=='meeting')return;const beat=()=>action('heartbeat');beat();const timer=setInterval(beat,20000);return()=>clearInterval(timer);},[view]);
  useEffect(() => { if (previewRef.current) { previewRef.current.srcObject = local; previewRef.current.play().catch(() => {}); } }, [local,view]);
  useEffect(() => { document.documentElement.dataset.theme = mode; document.documentElement.dataset.palette = palette; try { localStorage.setItem('skymeet-mode',mode); localStorage.setItem('skymeet-palettes',JSON.stringify(palettes)); } catch {} document.querySelector('meta[name="theme-color"]')?.setAttribute('content', getComputedStyle(document.documentElement).getPropertyValue('--bg').trim()); }, [mode,palette,palettes]);
  useEffect(() => { const listener = e => { if (view !== 'meeting') return; e.preventDefault(); e.returnValue = ''; }; window.addEventListener('beforeunload',listener); return () => window.removeEventListener('beforeunload',listener); }, [view]);
  async function acquireMedia(useVideo = true, useAudio = true, selectedAudio = audioDevice, selectedVideo = videoDevice) {
    if (!navigator.mediaDevices?.getUserMedia) return notify('Camera/microphone require HTTPS or localhost and a supported browser.');
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: useAudio ? { deviceId: selectedAudio ? { exact:selectedAudio } : undefined, echoCancellation:true, noiseSuppression:true, autoGainControl:true } : false, video:useVideo ? { deviceId:selectedVideo ? { exact:selectedVideo } : undefined,width:{ideal:640},height:{ideal:360},frameRate:{ideal:20,max:24} } : false });
      const old = localRef.current; localRef.current = stream; setLocal(stream); setMic(useAudio); setCamera(useVideo); await meshRef.current?.media(stream,screenRef.current); old?.getTracks().forEach(t => t.stop());
      setDevices(await navigator.mediaDevices.enumerateDevices());
      if (socketRef.current?.connected) action('media',{mic:useAudio,camera:useVideo});
      stream.getTracks().forEach(t => t.addEventListener('ended',() => { if (t.kind === 'video') { setCamera(false); action('media',{camera:false}); } else { setMic(false); action('media',{mic:false}); } }));
    } catch (e) { notify(`Could not access ${useVideo ? 'camera/microphone' : 'microphone'}: ${e.name}. Check permissions, or join without them.`); }
  }
  async function toggle(kind) {
    const stream = localRef.current, track = kind === 'mic' ? stream?.getAudioTracks()[0] : stream?.getVideoTracks()[0];
    if (!track || track.readyState === 'ended') return acquireMedia(kind === 'camera' || camera,kind === 'mic' || mic);
    track.enabled = !track.enabled; if (kind === 'mic') setMic(track.enabled); else setCamera(track.enabled);
    if (socketRef.current?.connected) action('media',{[kind]:track.enabled});
  }
  async function createMeeting(e) { e.preventDefault(); setBusy(true); try { const r = await request('/api/rooms',{title,password,hostKey,permanent}); storage.set(`host:${r.code}`,r.hostToken);rememberRoom(r); setCode(r.code); setRoom(r); history.replaceState({},'',`/meet/${r.code}`); setView('prejoin'); } catch(e) { notify(e.message); } finally { setBusy(false); } }
  function openMeeting(e) { e.preventDefault(); const c = parseCode(joinCode); if (!/^[a-f0-9]{6}-[a-f0-9]{6}-[a-f0-9]{6}$/.test(c)) return notify('Enter a valid meeting link or code.'); setPassword(''); setCode(c); history.replaceState({},'',`/meet/${c}`); setView('prejoin'); }
  function cleanup() { setShowBoard(false); meshRef.current?.close(); meshRef.current = null; socketRef.current?.disconnect(); socketRef.current = null; localRef.current?.getTracks().forEach(t => t.stop()); localRef.current = null; setLocal(null); screenRef.current?.getTracks().forEach(t => t.stop()); screenRef.current = null; setScreen(null); if (recordRef.current?.state === 'recording') recordRef.current.stop(); clearInterval(timerRef.current); noteSync.current?.cancel(); setRemotes({}); }
  function join() {
    if (!name.trim()) return notify('Enter your display name.');
    setBusy(true); storage.set('displayName',name.trim());
    socketRef.current?.disconnect(); const socket = io({ autoConnect:false }); socketRef.current = socket;
    joinData.current = { code, participantKey:participantKey(), name:name.trim(), password, hostToken:storage.get(`host:${code}`), resumeToken:storage.get(`resume:${code}`) };
    socket.on('connect',() => { setOnline(true); socket.timeout(10000).emit('join',joinData.current,(err,res) => { setBusy(false); if (err || !res?.ok) { const error = res?.error || 'Join timed out. Try again.'; setFatal(error); notify(error); cleanup(); setView('prejoin'); } else { joinData.current.resumeToken = res.resumeToken; storage.set(`resume:${code}`,res.resumeToken); } }); });
    socket.on('connect_error',() => { setBusy(false); setOnline(false); notify('Cannot reach server. It may be waking up; reconnection will retry automatically.'); });
    socket.on('disconnect',() => { setOnline(false); meshRef.current?.close(); meshRef.current = null; });
    socket.on('waiting-room',() => { setBusy(false); setView('waiting'); });
    socket.on('admitted',data => {
      meshRef.current?.close(); setRemotes({}); setConnections({}); setSelfId(data.selfId); setMessages(data.messages); setBoard(data.board); noteSync.current.attach(code,data); setPoll(data.poll);setWhiteboard(data.whiteboard||{objects:[],revision:0,enabled:true});setCursors({}); setView('meeting'); setBusy(false); setWaiting([]);
      meshRef.current = new Mesh(socket,data.iceServers,{
        stream:(id,camera,screen) => setRemotes(prev => ({...prev,[id]:{camera,screen}})),
        connection:(id,status) => setConnections(prev => ({...prev,[id]:status})),
        remove:id => setRemotes(prev => { const next = {...prev}; delete next[id]; return next; }),
        error:msg => notify(`Media connection: ${msg}`)
      });
      meshRef.current.media(localRef.current,screenRef.current).catch(e => notify(e.message));
      action('media',{mic:!!localRef.current?.getAudioTracks()[0]?.enabled,camera:!!localRef.current?.getVideoTracks()[0]?.enabled,sharing:!!screenRef.current,recording:recordRef.current?.state === 'recording'});
    });
    socket.on('state',state => { setMeeting(state);setWhiteboard(prev=>({...prev,enabled:state.boardEnabled})); meshRef.current?.sync(state.participants).catch(e => notify(e.message)); clearInterval(timerRef.current); const update = () => setElapsed(Math.max(0,Math.floor((Date.now()-state.createdAt)/1000))); update(); timerRef.current = setInterval(update,1000); });
    socket.on('board-state',setWhiteboard);socket.on('cursor',c=>setCursors(prev=>({...prev,[c.id]:{...c,at:Date.now()}})));socket.on('storage-error',setStorageWarning);
    socket.on('waiting',setWaiting); socket.on('chat',msg => setMessages(prev => [...prev.slice(-199),msg])); socket.on('reaction',r => notify(`${r.emoji} ${r.name}`)); socket.on('draw',stroke => setBoard(prev => [...prev,stroke])); socket.on('board',setBoard); socket.on('notes-state',state => noteSync.current.receive(state)); socket.on('poll',setPoll);
    socket.on('control',d => { if (d.action === 'mute') { localRef.current?.getAudioTracks().forEach(t => { t.enabled = false; }); setMic(false); action('media',{mic:false}); notify('The host muted your microphone.'); } if (d.action === 'request-unmute') notify('The host asked you to unmute. Use the microphone button when ready.'); if (d.action === 'stop-sharing') { stopShare(); notify('Screen sharing was disabled by the host.'); } });
    socket.on('ended',reason => { cleanup(); setFatal(reason); setView('ended'); });
    socket.connect();
  }
  async function stopShare() { const old = screenRef.current; screenRef.current = null; setScreen(null); await meshRef.current?.media(localRef.current,null); old?.getTracks().forEach(t => t.stop()); if (socketRef.current?.connected) action('media',{sharing:false}); }
  async function share() {
    if (screenRef.current) return stopShare();
    if (!navigator.mediaDevices?.getDisplayMedia) return notify('Screen sharing is not supported in this browser. Try desktop Chrome or Edge.');
    try { const stream = await navigator.mediaDevices.getDisplayMedia({ video:true,audio:true }); screenRef.current = stream; setScreen(stream); await meshRef.current?.media(localRef.current,stream); stream.getVideoTracks()[0].onended = () => stopShare().catch(e => notify(e.message)); action('media',{sharing:true}); } catch(e) { if (e.name !== 'NotAllowedError') notify(`Screen share failed: ${e.message}`); }
  }
  async function record() {
    if (recordRef.current?.state === 'recording') { recordRef.current.stop(); return; }
    if (!navigator.mediaDevices?.getDisplayMedia || !window.MediaRecorder) return notify('Recording requires a desktop browser supporting screen capture and MediaRecorder.');
    if (!confirm('Get everyone’s permission before recording. This records the screen/tab you select and only the audio offered by your browser. It may not include your microphone. Select this meeting tab and enable tab audio. All participants will see a REC indicator. Continue only with consent.')) return;
    try {
      const capture = await navigator.mediaDevices.getDisplayMedia({ video:true,audio:true }); const chunks = [];
      const mimeType = ['video/webm;codecs=vp9,opus','video/webm','video/mp4'].find(t => MediaRecorder.isTypeSupported(t));
      const recorder = new MediaRecorder(capture,mimeType ? {mimeType} : undefined); recordRef.current = recorder;
      recorder.ondataavailable = e => { if(e.data.size) chunks.push(e.data); };
      let limitTimer;
      recorder.onstop = () => { clearTimeout(limitTimer); capture.getTracks().forEach(t => t.stop()); setRecording(false); if (socketRef.current?.connected) action('media',{recording:false}); const ext = recorder.mimeType.includes('mp4') ? 'mp4' : 'webm'; download(`skymeet-${Date.now()}.${ext}`,new Blob(chunks,{type:recorder.mimeType})); recordRef.current = null; };
      capture.getVideoTracks()[0].onended = () => { if (recorder.state === 'recording') recorder.stop(); };
      recorder.start(1000); setRecording(true); action('media',{recording:true});
      limitTimer = setTimeout(() => { if(recorder.state === 'recording') { recorder.stop(); notify('Recording saved at the 20-minute safety limit. You can start another.'); } },20*60000);
    } catch(e) { if(e.name !== 'NotAllowedError') notify(`Recording failed: ${e.message}`); }
  }
  async function copyLink() { try { await navigator.clipboard.writeText(`${location.origin}/meet/${code}`); notify('Meeting link copied. Share the password separately if set.'); } catch { notify(`Copy this address: ${location.origin}/meet/${code}`); } }
  async function attendance() { try { const {rows} = await send('attendance'); download('skymeet-attendance.csv', '\uFEFFName,Joined,Left,Duration minutes\n' + rows.map(r => [r.name,new Date(r.joinedAt).toISOString(),r.leftAt ? new Date(r.leftAt).toISOString() : 'Present',(( (r.leftAt || Date.now())-r.joinedAt)/60000).toFixed(1)].map(csv).join(',')).join('\n'),'text/csv'); } catch(e) { notify(e.message); } }
  async function leave() { if (recording && !confirm('Leaving will stop and download your recording. Continue?')) return; if(!await noteSync.current.flush()&&!confirm('Your notes draft has not been saved. Leave without saving it?'))return; cleanup(); setFatal('You left the meeting.'); setView('ended'); }
  function setNote(text) { noteSync.current.edit(text); }
  const meetingControls = <><IconButton icon={mic ? Mic : MicOff} label={mic ? 'Mute microphone' : 'Unmute microphone'} active={mic} onClick={() => toggle('mic')}/><IconButton icon={camera ? Video : VideoOff} label={camera ? 'Turn camera off' : 'Turn camera on'} active={camera} onClick={() => toggle('camera')}/></>;
  async function boardSend(event,data){const result=await send(event,data);if(result.objects)setWhiteboard(result);return result;}
  async function privateLink(roomCode=code){const key=storage.get('host:'+roomCode);if(!key)return notify('No host key saved in this browser.');if(!confirm('This private recovery link grants host access. Save it securely and never share it with students. Continue?'))return;const link=location.origin+'/meet/'+roomCode+'#host='+encodeURIComponent(key);try{await navigator.clipboard.writeText(link);notify('Private host recovery link copied.');}catch{download('private-host-recovery-link.txt',link);}}
  const attendanceModal=attendanceLoader&&<Attendance load={attendanceLoader} onClose={()=>setAttendanceLoader(null)}/>;
  const themeControls = <nav className="academy-navigation" aria-label="Appearance"><select className="theme-select" aria-label="Color theme" value={palette} onChange={e => setPalettes(p => ({...p,[mode]:e.target.value}))}>{PALETTES.map(([id,dark,label]) => <option key={id} value={id}>{light ? label : dark}</option>)}</select><button type="button" className="theme-toggle" aria-label={light ? 'Switch to dark mode' : 'Switch to light mode'} title={light ? 'Switch to dark mode' : 'Switch to light mode'} onClick={() => setLight(!light)}>{light ? <Moon size={18}/> : <Sun size={18}/>}<span>{light ? 'Dark mode' : 'Light mode'}</span></button></nav>;
  const toastElement = toast && <div className="toast" role="status">{toast}<button aria-label="Dismiss notification" onClick={() => setToast('')}><X size={16}/></button></div>;
  if (view === 'home') return <div className="landing"><header className="site-header"><Brand/>{themeControls}</header><main>
    <div className="hero"><section className="hero-copy"><div className="eyebrow"><span className="live-dot"/> MEET. THINK. CREATE.</div><h1>Connect with purpose.<br/>Think together.<br/><em>Make room for ideas.</em></h1><p>Your shared space for conversations, bright ideas, and better teamwork. Meet face to face and bring everyone onto the same canvas.</p><div className="hero-pills"><span><ShieldCheck size={16}/> Host-approved entry</span><span><Zap size={16}/> No app installation</span></div><div className="channel-card"><div className="channel-avatar">SM<span>↗</span></div><div><strong>A little space. Endless possibilities.</strong><p>Video, canvas, notes, and chat. Together.</p></div></div></section>
    <section className="launch-card"><div className="card-head"><Radio size={22}/><span>YOUR SHARED SPACE</span></div><h2>A space for great ideas.</h2><form onSubmit={createMeeting}><label>Room name<input value={title} onChange={e => setTitle(e.target.value)} maxLength={80} required placeholder="Weekly team catch-up"/></label><div className="two-fields"><label>Your name<input value={name} onChange={e => setName(e.target.value)} maxLength={40} required placeholder="What should we call you?"/></label><label>Room password <span>optional</span><input type="password" value={password} onChange={e => setPassword(e.target.value)} maxLength={128} autoComplete="new-password" placeholder="Extra privacy"/></label></div>{config?.hostKeyRequired && <label>Host access key<input type="password" value={hostKey} onChange={e => setHostKey(e.target.value)} autoComplete="off" required placeholder="From your Render environment settings"/></label>}<label className="room-permanence"><input type="checkbox" checked={permanent} disabled={!config?.permanentRooms} onChange={e=>setPermanent(e.target.checked)}/> Permanent room link</label><p className="muted">{config?.permanentRooms?'Reusable links, board and attendance saved in PostgreSQL.':'Temporary mode. Set DATABASE_URL on Render to enable permanent links and saved history.'}</p><button className="primary wide" disabled={busy || !config}><Plus size={19}/>{busy ? 'Creating your room…' : 'Start a meeting'}<ArrowUpRight size={19}/></button></form><div className="divider"><span>JOIN A MEETING</span></div><form className="join-form" onSubmit={openMeeting}><input aria-label="Meeting link or code" placeholder="Paste a meeting link or code" value={joinCode} onChange={e => setJoinCode(e.target.value)} required/><button className="join-button" aria-label="Join meeting"><ArrowRight size={21}/></button></form><p className="small-muted">Up to {config?.maxParticipants || 8} people · No meeting subscription</p></section></div>
    <section className="saved-rooms"><h2>Your rooms</h2><p className="muted">Saved in this browser. Keep a private recovery link for host access on another device. Shared computers retain these host keys until you remove them.</p>{savedRooms().length===0?<p>No saved rooms yet. Create one above.</p>:savedRooms().map(r=><div className="saved-room" key={r.code}><div><strong>{r.title}</strong><small>{r.permanent?'Permanent room':'Temporary room'} · {r.code}</small></div><a className="primary" href={'/meet/'+r.code}>Open</a><button onClick={()=>privateLink(r.code)}>Private host link</button><button onClick={()=>setAttendanceLoader(()=>()=>request('/api/rooms/'+r.code+'/attendance',{hostToken:storage.get('host:'+r.code)}))}>Attendance history</button><button onClick={()=>{if(confirm('Remove this room and its host key from this browser? Your room on the server is not deleted. Save your private host recovery link first.')){localStorage.removeItem('host:'+r.code);localStorage.setItem('academy-classrooms',JSON.stringify(savedRooms().filter(v=>v.code!==r.code)));notify('Removed from this browser.');}}}>Forget</button></div>)}</section>
    <section className="feature-strip"><div><MonitorUp/><strong>Bring your ideas to life.</strong><p>Share your screen, concepts, and presentations.</p></div><div><MessageSquare/><strong>Keep everyone in the conversation.</strong><p>Chat, reactions, notes, and a shared whiteboard.</p></div><div><ShieldCheck/><strong>A welcoming space for everyone.</strong><p>Waiting room, room lock, and co-host controls.</p></div></section>
    <div className="hosting-note"><span className="status-dot"/> {config?.permanentRooms?'DATABASE CONNECTED':'TEMPORARY MODE'} <span>{config?.permanentRooms?'Permanent rooms retain boards, notes and attendance across restarts.':'Set DATABASE_URL for permanent storage. Temporary rooms disappear on restart.'}</span></div>
    </main><footer><span>SkyMeet <span className="muted">/ Your space to connect</span></span><span>Meet. Think. Create.</span></footer>{toastElement}{attendanceModal}</div>;

  if (view === 'prejoin' || view === 'waiting') return <div className="prejoin-page"><header className="site-header"><Brand/>{themeControls}</header><main className="prejoin"><section><div className="preview"><video ref={previewRef} autoPlay playsInline muted className={!camera ? 'hidden-video' : 'mirror'}/>{!camera && <div className="preview-placeholder"><div className="avatar">{initials(name || 'SM')}</div><p>Your camera is off</p></div>}<div className="preview-controls">{meetingControls}</div></div><div className="row spaced"><button onClick={() => acquireMedia()}><Video size={16}/> Enable camera & mic</button><button onClick={() => acquireMedia(false,true)}><Mic size={16}/> Audio only</button></div><p className="muted">Preview is private until you’re admitted. Headphones help prevent echoes.</p></section><section className="prejoin-info"><div className="eyebrow">{view === 'waiting' ? 'HANG TIGHT' : 'YOU’RE ALMOST IN'}</div><h1>{room?.title || 'Join your room.'}</h1>{fatal ? <p className="error" role="alert">{fatal}</p> : view === 'waiting' ? <><div className="waiting-pulse"><Radio size={28}/></div><h2>Waiting for the host</h2><p className="muted">The host will let you in shortly. You can still adjust your camera and microphone.</p><button onClick={leave}>Cancel request</button></> : <><label>Your name<input value={name} onChange={e => setName(e.target.value)} maxLength={40} placeholder="Enter your name"/></label>{room?.passwordRequired && !storage.get(`host:${code}`) && <label>Meeting password<input type="password" value={password} onChange={e => setPassword(e.target.value)}/></label>}<button className="primary wide" onClick={join} disabled={busy || !room}>{busy ? 'Connecting…' : storage.get(`host:${code}`) ? 'Enter your room' : 'Ask to join'}<ArrowRight size={18}/></button><p className="notice">{room?.permanent?'Permanent link: reuse this address for future meetings.':'Temporary room: link expires after the server restarts.'}</p><p className="muted">Joining shares your display name with the room. Recording requires everyone’s permission.</p>{config && !config.turnConfigured && <p className="notice">Direct-call mode: some work, school, or mobile networks need a TURN relay. Ask the host if calls don’t connect.</p>}</>}<a href="/" className="text-link">Back to home</a></section></main>{toastElement}</div>;

  if (view === 'ended') return <div className="end-page"><header className="end-header"><Brand/>{themeControls}</header><div className="end-card"><div className="end-icon"><Check size={32}/></div><h1>Thanks for meeting with us.</h1><p>{fatal}</p><a className="primary" href="/">Back to SkyMeet <ArrowRight size={18}/></a></div>{toastElement}</div>;

  const sorted = [...(meeting?.participants || [])].sort((a,b) => (b.id === pinned ? 2 : b.sharing ? 1 : 0) - (a.id === pinned ? 2 : a.sharing ? 1 : 0));
  return <div className="meeting-page"><header className="meeting-header"><Brand/><div className="meeting-title"><strong>{meeting?.title}</strong><span><span className="live-dot"/>{online ? 'LIVE ROOM' : 'RECONNECTING'}<span className="timer">{Math.floor(elapsed/60)}:{String(elapsed%60).padStart(2,'0')}</span></span></div><div className="row"><button className="invite-button" onClick={copyLink}><Copy size={16}/><span>Invite participants</span></button>{themeControls}</div></header>
    {storageWarning&&<div className="storage-warning" role="alert">{storageWarning}<button onClick={()=>setStorageWarning('')}>Dismiss</button></div>}
    {!online && <div className="connection-banner" role="alert">Connection interrupted. Reconnecting automatically… If the server restarted, the host needs to create a new meeting.</div>}
    {meeting?.participants.some(p => p.recording) && <div className="recording-banner">● A participant is recording. Only continue if you consent; you can leave at any time.</div>}
    <div className="meeting-body"><main className="stage"><div className={`video-grid count-${sorted.length} ${pinned || sorted.some(p => p.sharing) ? 'focus-grid' : ''}`}>{sorted.map((p,i) => <VideoTile key={p.id} participant={p} camera={p.id === selfId ? local : remotes[p.id]?.camera} screen={p.id === selfId ? screen : remotes[p.id]?.screen} self={p.id === selfId} connection={connections[p.id]} pinned={i === 0 && !!(pinned || sorted.some(p => p.sharing))} onPin={() => setPinned(pinned === p.id ? '' : p.id)}/>)}</div>{sorted.length === 1 && <div className="alone-note"><Radio size={17}/><span>The room’s ready. Share the link with your students or colleagues.</span><button onClick={copyLink}>Copy invite</button></div>}<div className="stage-caption"><span><ShieldCheck size={14}/> Host-approved room · {code}</span><span>MEET. THINK. CREATE.</span></div></main>
    {panel && <aside className="side-panel"><div className="panel-heading"><h2>{{people:'Participants',chat:'Room chat',board:'Whiteboard',notes:'Shared notes',poll:'Quick poll',settings:'Room settings'}[panel]}</h2><IconButton icon={X} label="Close panel" onClick={() => setPanel('')}/></div><div className="panel-content">
    {panel === 'people' && <>{host && waiting.length > 0 && <section className="waiting-list"><h3>Waiting to join · {waiting.length}</h3>{waiting.map(p => <div className="waiting-person" key={p.id}><strong>{p.name}</strong><div className="row"><button onClick={() => action('admit',{id:p.id})}>Admit</button><button onClick={() => action('reject',{id:p.id})}>Decline</button></div></div>)}</section>}<div className="panel-section-label">IN THE ROOM · {sorted.length}</div>{meeting?.participants.map(p => <div className="person" key={p.id}><div className="person-summary"><span className="small-avatar">{initials(p.name)}</span><div><strong>{p.name}{p.id === selfId ? ' (you)' : ''}</strong><small>{p.role === 'guest' ? 'Participant' : p.role}</small></div>{p.hand && <span>✋</span>}{!p.mic && <MicOff size={15}/>}</div>{host && p.id !== selfId && p.role !== 'host' && (self.role === 'host' || p.role === 'guest') && <div className="person-actions"><button onClick={() => action('control',{id:p.id,action:'mute'})}>Mute</button><button onClick={() => action('control',{id:p.id,action:'request-unmute'})}>Ask to unmute</button>{self.role === 'host' && <button onClick={() => action('control',{id:p.id,action:p.role === 'cohost' ? 'guest' : 'cohost'})}>{p.role === 'cohost' ? 'Remove co-host' : 'Make co-host'}</button>}<button className="text-danger" onClick={() => confirm(`Remove ${p.name}?`) && action('control',{id:p.id,action:'remove'})}>Remove</button></div>}</div>)}{host && <button className="secondary wide" onClick={() => sorted.filter(p => p.id !== selfId && p.role === 'guest').forEach(p => action('control',{id:p.id,action:'mute'}))}>Mute participants</button>}<p className="muted">Participants may unmute themselves. Host controls cannot remotely activate a microphone or camera.</p></>}
    {panel === 'chat' && <><p className="notice">Chat is visible to everyone in this session and is not retained between sessions.</p><div className="messages">{messages.length === 0 && <div className="empty-panel"><MessageSquare/><p>Ask a question or share an idea.</p></div>}{messages.map(m => <div className="message" key={m.id}><div><strong>{m.name}</strong><time>{fmtTime(m.at)}</time></div><p>{m.text}</p></div>)}</div><form className="chat-form" onSubmit={e => { e.preventDefault(); send('chat',{text:message}).then(() => setMessage('')).catch(e => notify(e.message)); }}><input aria-label="Chat message" value={message} onChange={e => setMessage(e.target.value)} maxLength={2000} placeholder="Say something…" disabled={!meeting?.chatEnabled && !host}/><button aria-label="Send message" disabled={!message.trim()}><Send size={18}/></button></form><button className="text-button" onClick={() => download('skymeet-chat.txt',messages.map(m => `[${fmtTime(m.at)}] ${m.name}: ${m.text}`).join('\n'))}><Download size={15}/> Download chat</button></>}
    {panel === 'board' && <><h3>Collaborative whiteboard</h3><p className="muted">Sticky notes, text, shapes, connected arrows, drawing, images, frames, templates, undo/redo and exports on a pan-and-zoom canvas.</p><button className="primary wide" onClick={()=>setShowBoard(true)}>Open full whiteboard</button><p className="muted">{meeting?.permanent?'This board is retained for future sessions.':'Temporary room: export your board before leaving.'}</p></>}
    {panel === 'notes' && <><p className="muted">Shared with everyone. Conflicting edits keep your draft for review.</p><p role="status" className="muted">{noteState.status}</p>{noteState.conflict&&<div className="notice notes-conflict"><p>Another participant saved changes. Compare before replacing them.</p><details><summary>View latest shared notes</summary><pre style={{whiteSpace:'pre-wrap'}}>{noteState.remoteText}</pre></details><div className="row"><button onClick={()=>noteSync.current.useLatest()}>Use latest notes</button><button onClick={()=>noteSync.current.replaceWithDraft()}>Save my draft instead</button></div></div>}<textarea className="notes" aria-label="Shared meeting notes" maxLength={12000} placeholder="Ideas, action items, things worth remembering…" value={notes} onChange={e => setNote(e.target.value)}/><button disabled={!noteState.dirty||noteState.conflict} onClick={()=>noteSync.current.flush()}>Save notes now</button><button onClick={() => download('skymeet-notes.txt',notes)}><Download size={16}/> Download notes</button></>}
    {panel === 'poll' && <>{poll ? <div className="poll"><h3>{poll.question}</h3>{poll.choices.map((choice,i) => <button className="poll-choice" key={i} disabled={poll.closed} onClick={() => action('poll-vote',{choice:i})}><span>{choice}</span><strong>{poll.counts[i]}</strong><span className="poll-bar" style={{width:`${poll.total ? poll.counts[i]/poll.total*100 : 0}%`}}/></button>)}<p className="muted">{poll.total} vote{poll.total === 1 ? '' : 's'} · {poll.closed ? 'Closed' : 'Vote again to change your choice'}</p>{host && !poll.closed && <button onClick={() => action('poll-close')}>Close poll</button>}</div> : <div className="empty-panel"><BarChart3/><p>No poll yet. The host can start one.</p></div>}{host && <form className="poll-form" onSubmit={e => { e.preventDefault(); action('poll-create',{question:pollQuestion,choices:pollChoices.split('\n')}); }}><h3>{poll ? 'Replace with a new poll' : 'Ask the room'}</h3><label>Question<input value={pollQuestion} onChange={e => setPollQuestion(e.target.value)} maxLength={180} required/></label><label>Choices (one per line, up to 6)<textarea value={pollChoices} onChange={e => setPollChoices(e.target.value)} required/></label><button className="primary">Launch poll</button></form>}</>}
    {panel === 'settings' && <><h3>Your devices</h3><label>Microphone<select value={audioDevice} onChange={e => setAudioDevice(e.target.value)}><option value="">System default</option>{devices.filter(d => d.kind === 'audioinput').map((d,i) => <option key={d.deviceId || i} value={d.deviceId}>{d.label || `Microphone ${i+1}`}</option>)}</select></label><label>Camera<select value={videoDevice} onChange={e => setVideoDevice(e.target.value)}><option value="">System default</option>{devices.filter(d => d.kind === 'videoinput').map((d,i) => <option key={d.deviceId || i} value={d.deviceId}>{d.label || `Camera ${i+1}`}</option>)}</select></label><button onClick={() => acquireMedia(true,true)}>Apply devices & enable media</button><p className="muted">Noise suppression and echo cancellation are requested automatically where supported. Speaker selection uses your device’s system settings.</p>{host && <><h3>Host controls</h3>{[['locked','Lock meeting'],['chatEnabled','Allow participant chat'],['shareEnabled','Allow participant screen sharing'],['boardEnabled','Allow participant board editing']].map(([key,label]) => <label className="toggle-row" key={key}>{label}<input type="checkbox" checked={meeting[key]} onChange={e => action('settings',{[key]:e.target.checked})}/></label>)}<button onClick={()=>setAttendanceLoader(()=>()=>send('attendance'))}><Users size={16}/> Attendance tracker & history</button><button onClick={()=>privateLink()}>Copy private host recovery link</button></>}<h3>Before you leave</h3><p className="muted">{meeting?.permanent?'Your room board, notes and attendance are saved. Chat and polls are session-only.':'This room is temporary. Download chat, notes, attendance, and your board before leaving.'} Local recording captures your chosen surface, not an automatic all-participant mix.</p></>}
    </div></aside>}
    </div><footer className="meeting-footer"><div className="footer-left"><span className="status-dot"/> {online ? 'Connected' : 'Reconnecting'}</div><div className="call-controls">{meetingControls}<span className="control-divider"/><IconButton icon={MonitorUp} label={screen ? 'Stop sharing' : 'Share screen'} active={!!screen} disabled={!host && !meeting?.shareEnabled} onClick={share}/><IconButton icon={Hand} label={hand ? 'Lower hand' : 'Raise hand'} active={hand} onClick={() => { setHand(!hand); action('media',{hand:!hand}); }}/><IconButton icon={recording ? Square : Circle} label={recording ? 'Stop recording' : 'Record locally'} active={recording} onClick={record}/><div className="reaction-wrap"><button aria-label="Send applause" title="Send applause" onClick={() => action('reaction',{emoji:'👏'})}>👏</button></div><IconButton icon={PhoneOff} label="Leave meeting" danger onClick={leave}/>{host && <button className="end-button" onClick={async () => {if(!await noteSync.current.flush()){notify('Save or resolve your notes draft before ending the meeting.');return;}confirm(meeting?.permanent?'End this session for everyone? The room link, board, notes and attendance will remain.':'End this temporary meeting for everyone? Download your reports first.') && action('end');}}>End for all</button>}</div><div className="panel-controls">{[[Users,'people','Participants'],[MessageSquare,'chat','Chat'],[Pencil,'board','Whiteboard'],[NotebookPen,'notes','Notes'],[BarChart3,'poll','Polls'],[Settings,'settings','Settings']].map(([icon,key,label]) => <IconButton key={key} icon={icon} label={label} active={panel === key} onClick={() => setPanel(panel === key ? '' : key)}>{key === 'people' && waiting.length > 0 && host && <span className="badge">{waiting.length}</span>}</IconButton>)}{host&&<IconButton icon={Download} label="Attendance tracker" onClick={()=>setAttendanceLoader(()=>()=>send('attendance'))}/>}<IconButton icon={Maximize} label="Fullscreen" onClick={() => { const task = document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen?.(); task?.catch(() => notify('Fullscreen is not available.')); }}/></div></footer>{toastElement}{showBoard&&<BoardStudio state={whiteboard} connected={online} recording={meeting?.participants.some(p=>p.recording)} send={boardSend} host={host} notify={notify} cursors={cursors} onClose={()=>setShowBoard(false)}/ >}{attendanceModal}</div>;
}
createRoot(document.getElementById('root')).render(<App/>);
