import React, { useState, useEffect, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import { io } from 'socket.io-client';
import { Mic, MicOff, Video, VideoOff, MonitorUp, PhoneOff, Users, MessageSquare, Hand, Copy, ArrowUpRight, ArrowRight, Plus, ShieldCheck, Radio, X, Send, Settings, Lock, Unlock, Circle, Square, Download, Pencil, BarChart3, NotebookPen, Maximize, Pin, Volume2, Check, Youtube, Zap, Sun, Moon } from 'lucide-react';
import { Mesh } from './rtc';
import './style.css';

const CHANNEL = 'https://www.youtube.com/@supremegenz';
const storage = { get: k => { try { return sessionStorage.getItem(k); } catch { return null; } }, set: (k,v) => { try { sessionStorage.setItem(k,v); } catch {} } };
function download(name, text, type = 'text/plain') { const url = URL.createObjectURL(text instanceof Blob ? text : new Blob([text], { type })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 10000); }
const parseCode = value => { try { return new URL(value).pathname.split('/').filter(Boolean).pop(); } catch { return value.trim().split('/').filter(Boolean).pop() || ''; } };
const initials = name => name.split(/\s+/).map(s => s[0]).slice(0, 2).join('').toUpperCase();
const csv = value => '"' + String(value).replace(/^[=+@\-\t\r]/, "'$&").replaceAll('"', '""') + '"';
const fmtTime = t => new Date(t).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
function Brand() { return <a className="brand" href="/" aria-label="Supreme Meet home"><img src="/icon.svg" alt=""/><span>SUPREME<span className="brand-sub">MEET</span></span></a>; }
function IconButton({ icon: Icon, label, active, danger, onClick, disabled, children }) { return <button type="button" title={label} aria-label={label} aria-pressed={active === undefined ? undefined : active} className={`icon-button ${active ? 'active' : ''} ${danger ? 'danger' : ''}`} onClick={onClick} disabled={disabled}><Icon size={20}/>{children}</button>; }
function VideoTile({ participant, camera, screen, self, connection, pinned, onPin }) {
  const video = useRef(null), audio = useRef(null), [blocked, setBlocked] = useState(false);
  const isScreen = participant.sharing && screen;
  const visible = !!isScreen || participant.camera;
  useEffect(() => { const v = video.current; if (!v) return; v.srcObject = isScreen ? screen : camera; v.play().then(() => setBlocked(false)).catch(() => setBlocked(true)); }, [camera, screen, isScreen, visible]);
  useEffect(() => { const a = audio.current; if (!a || self) return; a.srcObject = camera; a.play().catch(() => setBlocked(true)); }, [camera, self]);
  return <article className={`tile ${pinned ? 'pinned' : ''} ${participant.hand ? 'raised' : ''}`} data-testid="video-tile">
    <video ref={video} autoPlay playsInline muted={!isScreen || self} className={`${!visible ? 'hidden-video' : ''} ${self && !isScreen ? 'mirror' : ''}`}/>
    {!self && <audio ref={audio} autoPlay/>}
    {!visible && <div className="avatar">{initials(participant.name)}</div>}
    <div className="tile-top"><span>{participant.role !== 'guest' && <span className="role">{participant.role === 'host' ? 'HOST' : 'CO-HOST'}</span>}{participant.hand && <span className="hand-tag">✋</span>}{participant.recording && <span className="record-tag">● REC</span>}</span><IconButton icon={Pin} label={`Pin ${participant.name}`} active={pinned} onClick={onPin}/></div>
    <div className="tile-caption"><span>{participant.name}{self ? ' (you)' : ''}{isScreen ? ' · presenting' : ''}</span><span className="tile-status">{!self && <small>{connection || 'connecting'}</small>}{participant.mic ? <Mic size={15}/> : <MicOff size={15}/>}</span></div>
    {blocked && <button className="play-audio" onClick={() => { video.current?.play().catch(() => {}); audio.current?.play().catch(() => {}); setBlocked(false); }}>Tap to play media</button>}
  </article>;
}
function Whiteboard({ strokes, onStroke, onClear, host, notify }) {
  const ref = useRef(null), current = useRef([]), [color, setColor] = useState('#ed3047');
  function paint(stroke, ctx) { if (!stroke.points.length) return; ctx.strokeStyle = stroke.color; ctx.lineWidth = 3; ctx.lineCap = 'round'; ctx.lineJoin = 'round'; ctx.beginPath(); stroke.points.forEach(([x,y], i) => i ? ctx.lineTo(x * 1000,y * 650) : ctx.moveTo(x * 1000,y * 650)); ctx.stroke(); }
  useEffect(() => { const ctx = ref.current.getContext('2d'); ctx.fillStyle = '#faf9f6'; ctx.fillRect(0,0,1000,650); strokes.forEach(s => paint(s,ctx)); }, [strokes]);
  const point = e => { const r = ref.current.getBoundingClientRect(); return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)), Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))]; };
  return <div className="whiteboard"><div className="row"><label className="inline-label">Ink <input type="color" aria-label="Ink color" value={color} onChange={e => setColor(e.target.value)}/></label><button onClick={() => ref.current.toBlob(blob => blob && download('supreme-whiteboard.png',blob))}>Save PNG</button>{host && <button onClick={onClear}>Clear</button>}</div><canvas aria-label="Shared drawing board" ref={ref} width="1000" height="650" onPointerDown={e => { if (strokes.length >= 1000) return notify('Board is full. Ask the host to clear it.'); current.current = [point(e)]; e.currentTarget.setPointerCapture(e.pointerId); }} onPointerMove={e => { if (!current.current.length || current.current.length >= 399) return; const p = point(e); paint({ color, points: [current.current.at(-1),p] }, ref.current.getContext('2d')); current.current.push(p); }} onPointerUp={() => { if (current.current.length >= 2) onStroke({ points: current.current, color }); current.current = []; }} onPointerCancel={() => { current.current = []; }}/><p className="muted">Draw together. Download your work before the meeting ends.</p></div>;
}

function App() {
  const initialCode = location.pathname.startsWith('/meet/') ? parseCode(location.pathname) : '';
  const [view,setView] = useState(initialCode ? 'prejoin' : 'home'), [code,setCode] = useState(initialCode), [room,setRoom] = useState(null), [config,setConfig] = useState(null);
  const [name,setName] = useState(storage.get('displayName') || ''), [title,setTitle] = useState('Supreme hangout'), [password,setPassword] = useState(''), [hostKey,setHostKey] = useState(''), [joinCode,setJoinCode] = useState('');
  const [toast,setToast] = useState(''), [busy,setBusy] = useState(false), [fatal,setFatal] = useState(''), [local,setLocal] = useState(null), [mic,setMic] = useState(false), [camera,setCamera] = useState(false), [devices,setDevices] = useState([]), [audioDevice,setAudioDevice] = useState(''), [videoDevice,setVideoDevice] = useState('');
  const [meeting,setMeeting] = useState(null), [selfId,setSelfId] = useState(''), [remotes,setRemotes] = useState({}), [connections,setConnections] = useState({}), [waiting,setWaiting] = useState([]), [messages,setMessages] = useState([]), [message,setMessage] = useState(''), [panel,setPanel] = useState('people'), [screen,setScreen] = useState(null), [pinned,setPinned] = useState(''), [hand,setHand] = useState(false), [online,setOnline] = useState(true), [recording,setRecording] = useState(false), [board,setBoard] = useState([]), [notes,setNotes] = useState(''), [poll,setPoll] = useState(null), [pollQuestion,setPollQuestion] = useState(''), [pollChoices,setPollChoices] = useState('Yes\nNo'), [elapsed,setElapsed] = useState(0), [light,setLight] = useState(false);
  const socketRef = useRef(null), meshRef = useRef(null), localRef = useRef(null), screenRef = useRef(null), recordRef = useRef(null), timerRef = useRef(null), previewRef = useRef(null), noteTimer = useRef(null), notifyTimer = useRef(null), joinData = useRef(null), notesRef = useRef('');
  const notify = text => { setToast(text); clearTimeout(notifyTimer.current); notifyTimer.current = setTimeout(() => setToast(''), 6500); };
  const self = meeting?.participants.find(p => p.id === selfId);
  const host = self && self.role !== 'guest';
  async function request(path, data) { const res = await fetch(path, data ? { method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data) } : {}); const result = await res.json(); if (!res.ok) throw new Error(result.error || 'Request failed.'); return result; }
  function send(event, data = {}) { return new Promise((resolve,reject) => { if (!socketRef.current?.connected) return reject(new Error('Connection lost. Please wait for reconnection.')); socketRef.current.timeout(10000).emit(event,data,(err,res) => err ? reject(new Error('Server did not respond. Try again.')) : res?.ok ? resolve(res) : reject(new Error(res?.error || 'Action failed.'))); }); }
  function action(event,data) { return send(event,data).catch(e => notify(e.message)); }
  useEffect(() => { request('/api/config').then(setConfig).catch(() => notify('Server is starting. Refresh in a minute.')); return () => { socketRef.current?.disconnect(); meshRef.current?.close(); localRef.current?.getTracks().forEach(t => t.stop()); screenRef.current?.getTracks().forEach(t => t.stop()); clearInterval(timerRef.current); clearTimeout(noteTimer.current); }; }, []);
  useEffect(() => { if (view === 'prejoin' && code) request(`/api/rooms/${encodeURIComponent(code)}`).then(r => { setRoom(r); setFatal(''); }).catch(e => setFatal(e.message)); }, [code,view]);
  useEffect(() => { if (previewRef.current) { previewRef.current.srcObject = local; previewRef.current.play().catch(() => {}); } }, [local,view]);
  useEffect(() => { document.documentElement.dataset.theme = light ? 'light' : 'dark'; }, [light]);
  useEffect(() => { const listener = e => { if (view !== 'meeting') return; e.preventDefault(); e.returnValue = ''; }; window.addEventListener('beforeunload',listener); return () => window.removeEventListener('beforeunload',listener); }, [view]);
  async function acquireMedia(useVideo = true, useAudio = true, selectedAudio = audioDevice, selectedVideo = videoDevice) {
    if (!navigator.mediaDevices?.getUserMedia) return notify('Camera/microphone require HTTPS or localhost and a supported browser.');
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: useAudio ? { deviceId: selectedAudio ? { exact:selectedAudio } : undefined, echoCancellation:true, noiseSuppression:true, autoGainControl:true } : false, video:useVideo ? { deviceId:selectedVideo ? { exact:selectedVideo } : undefined,width:{ideal:640},height:{ideal:360},frameRate:{ideal:20,max:24} } : false });
      const old = localRef.current; localRef.current = stream; setLocal(stream); setMic(useAudio); setCamera(useVideo); await meshRef.current?.media(stream,screenRef.current); old?.getTracks().forEach(t => t.stop());
      setDevices(await navigator.mediaDevices.enumerateDevices());
      if (socketRef.current?.connected) action('media',{mic:useAudio,camera:useVideo});
      stream.getTracks().forEach(t => t.addEventListener('ended',() => { if (t.kind === 'video') { setCamera(false); action('media',{camera:false}); } else { setMic(false); action('media',{mic:false}); } }));
    } catch (e) { notify(`Could not access ${useVideo ? 'camera/microphone' : 'microphone'}: ${e.name}. Check permissions, or join without them.`); }
  }
  async function toggle(kind) {
    const stream = localRef.current, track = kind === 'mic' ? stream?.getAudioTracks()[0] : stream?.getVideoTracks()[0];
    if (!track || track.readyState === 'ended') return acquireMedia(kind === 'camera' || camera,kind === 'mic' || mic);
    track.enabled = !track.enabled; if (kind === 'mic') setMic(track.enabled); else setCamera(track.enabled);
    if (socketRef.current?.connected) action('media',{[kind]:track.enabled});
  }
  async function createMeeting(e) { e.preventDefault(); setBusy(true); try { const r = await request('/api/rooms',{title,password,hostKey}); storage.set(`host:${r.code}`,r.hostToken); setCode(r.code); setRoom(r); history.replaceState({},'',`/meet/${r.code}`); setView('prejoin'); } catch(e) { notify(e.message); } finally { setBusy(false); } }
  function openMeeting(e) { e.preventDefault(); const c = parseCode(joinCode); if (!/^[a-f0-9]{6}-[a-f0-9]{6}-[a-f0-9]{6}$/.test(c)) return notify('Enter a valid meeting link or code.'); setPassword(''); setCode(c); history.replaceState({},'',`/meet/${c}`); setView('prejoin'); }
  function cleanup() { meshRef.current?.close(); meshRef.current = null; socketRef.current?.disconnect(); socketRef.current = null; localRef.current?.getTracks().forEach(t => t.stop()); localRef.current = null; setLocal(null); screenRef.current?.getTracks().forEach(t => t.stop()); screenRef.current = null; setScreen(null); if (recordRef.current?.state === 'recording') recordRef.current.stop(); clearInterval(timerRef.current); clearTimeout(noteTimer.current); setRemotes({}); }
  function join() {
    if (!name.trim()) return notify('Enter your display name.');
    setBusy(true); storage.set('displayName',name.trim());
    socketRef.current?.disconnect(); const socket = io({ autoConnect:false }); socketRef.current = socket;
    joinData.current = { code, name:name.trim(), password, hostToken:storage.get(`host:${code}`), resumeToken:storage.get(`resume:${code}`) };
    socket.on('connect',() => { setOnline(true); socket.timeout(10000).emit('join',joinData.current,(err,res) => { setBusy(false); if (err || !res?.ok) { const error = res?.error || 'Join timed out. Try again.'; setFatal(error); notify(error); cleanup(); setView('prejoin'); } else { joinData.current.resumeToken = res.resumeToken; storage.set(`resume:${code}`,res.resumeToken); } }); });
    socket.on('connect_error',() => { setBusy(false); setOnline(false); notify('Cannot reach server. It may be waking up; reconnection will retry automatically.'); });
    socket.on('disconnect',() => { setOnline(false); meshRef.current?.close(); meshRef.current = null; });
    socket.on('waiting-room',() => { setBusy(false); setView('waiting'); });
    socket.on('admitted',data => {
      meshRef.current?.close(); setRemotes({}); setConnections({}); setSelfId(data.selfId); setMessages(data.messages); setBoard(data.board); setNotes(data.notes); notesRef.current = data.notes; setPoll(data.poll); setView('meeting'); setBusy(false); setWaiting([]);
      meshRef.current = new Mesh(socket,data.iceServers,{
        stream:(id,camera,screen) => setRemotes(prev => ({...prev,[id]:{camera,screen}})),
        connection:(id,status) => setConnections(prev => ({...prev,[id]:status})),
        remove:id => setRemotes(prev => { const next = {...prev}; delete next[id]; return next; }),
        error:msg => notify(`Media connection: ${msg}`)
      });
      meshRef.current.media(localRef.current,screenRef.current).catch(e => notify(e.message));
      action('media',{mic:!!localRef.current?.getAudioTracks()[0]?.enabled,camera:!!localRef.current?.getVideoTracks()[0]?.enabled,sharing:!!screenRef.current,recording:recordRef.current?.state === 'recording'});
    });
    socket.on('state',state => { setMeeting(state); meshRef.current?.sync(state.participants).catch(e => notify(e.message)); clearInterval(timerRef.current); const update = () => setElapsed(Math.max(0,Math.floor((Date.now()-state.createdAt)/1000))); update(); timerRef.current = setInterval(update,1000); });
    socket.on('waiting',setWaiting); socket.on('chat',msg => setMessages(prev => [...prev.slice(-199),msg])); socket.on('reaction',r => notify(`${r.emoji} ${r.name}`)); socket.on('draw',stroke => setBoard(prev => [...prev,stroke])); socket.on('board',setBoard); socket.on('notes',text => { notesRef.current = text; setNotes(text); }); socket.on('poll',setPoll);
    socket.on('control',d => { if (d.action === 'mute') { localRef.current?.getAudioTracks().forEach(t => { t.enabled = false; }); setMic(false); action('media',{mic:false}); notify('The host muted your microphone.'); } if (d.action === 'request-unmute') notify('The host asked you to unmute. Use the microphone button when ready.'); if (d.action === 'stop-sharing') { stopShare(); notify('Screen sharing was disabled by the host.'); } });
    socket.on('ended',reason => { cleanup(); setFatal(reason); setView('ended'); });
    socket.connect();
  }
  async function stopShare() { const old = screenRef.current; screenRef.current = null; setScreen(null); await meshRef.current?.media(localRef.current,null); old?.getTracks().forEach(t => t.stop()); if (socketRef.current?.connected) action('media',{sharing:false}); }
  async function share() {
    if (screenRef.current) return stopShare();
    if (!navigator.mediaDevices?.getDisplayMedia) return notify('Screen sharing is not supported in this browser. Try desktop Chrome or Edge.');
    try { const stream = await navigator.mediaDevices.getDisplayMedia({ video:true,audio:true }); screenRef.current = stream; setScreen(stream); await meshRef.current?.media(localRef.current,stream); stream.getVideoTracks()[0].onended = () => stopShare().catch(e => notify(e.message)); action('media',{sharing:true}); } catch(e) { if (e.name !== 'NotAllowedError') notify(`Screen share failed: ${e.message}`); }
  }
  async function record() {
    if (recordRef.current?.state === 'recording') { recordRef.current.stop(); return; }
    if (!navigator.mediaDevices?.getDisplayMedia || !window.MediaRecorder) return notify('Recording requires a desktop browser supporting screen capture and MediaRecorder.');
    if (!confirm('Get everyone’s permission before recording. This records the screen/tab you select and only the audio offered by your browser. It may not include your microphone. Select this meeting tab and enable tab audio. All participants will see a REC indicator. Continue only with consent.')) return;
    try {
      const capture = await navigator.mediaDevices.getDisplayMedia({ video:true,audio:true }); const chunks = [];
      const mimeType = ['video/webm;codecs=vp9,opus','video/webm','video/mp4'].find(t => MediaRecorder.isTypeSupported(t));
      const recorder = new MediaRecorder(capture,mimeType ? {mimeType} : undefined); recordRef.current = recorder;
      recorder.ondataavailable = e => { if(e.data.size) chunks.push(e.data); };
      let limitTimer;
      recorder.onstop = () => { clearTimeout(limitTimer); capture.getTracks().forEach(t => t.stop()); setRecording(false); if (socketRef.current?.connected) action('media',{recording:false}); const ext = recorder.mimeType.includes('mp4') ? 'mp4' : 'webm'; download(`supreme-meet-${Date.now()}.${ext}`,new Blob(chunks,{type:recorder.mimeType})); recordRef.current = null; };
      capture.getVideoTracks()[0].onended = () => { if (recorder.state === 'recording') recorder.stop(); };
      recorder.start(1000); setRecording(true); action('media',{recording:true});
      limitTimer = setTimeout(() => { if(recorder.state === 'recording') { recorder.stop(); notify('Recording saved at the 20-minute safety limit. You can start another.'); } },20*60000);
    } catch(e) { if(e.name !== 'NotAllowedError') notify(`Recording failed: ${e.message}`); }
  }
  async function copyLink() { try { await navigator.clipboard.writeText(`${location.origin}/meet/${code}`); notify('Meeting link copied. Share the password separately if set.'); } catch { notify(`Copy this address: ${location.origin}/meet/${code}`); } }
  async function attendance() { try { const {rows} = await send('attendance'); download('supreme-attendance.csv', '\uFEFFName,Joined,Left,Duration minutes\n' + rows.map(r => [r.name,new Date(r.joinedAt).toISOString(),r.leftAt ? new Date(r.leftAt).toISOString() : 'Present',(( (r.leftAt || Date.now())-r.joinedAt)/60000).toFixed(1)].map(csv).join(',')).join('\n'),'text/csv'); } catch(e) { notify(e.message); } }
  function leave() { if (recording && !confirm('Leaving will stop and download your recording. Continue?')) return; cleanup(); setFatal('You left the meeting.'); setView('ended'); }
  function setNote(text) { notesRef.current = text; setNotes(text); clearTimeout(noteTimer.current); noteTimer.current = setTimeout(() => action('notes',{text:notesRef.current}),500); }
  const meetingControls = <><IconButton icon={mic ? Mic : MicOff} label={mic ? 'Mute microphone' : 'Unmute microphone'} active={mic} onClick={() => toggle('mic')}/><IconButton icon={camera ? Video : VideoOff} label={camera ? 'Turn camera off' : 'Turn camera on'} active={camera} onClick={() => toggle('camera')}/></>;
  const toastElement = toast && <div className="toast" role="status">{toast}<button aria-label="Dismiss notification" onClick={() => setToast('')}><X size={16}/></button></div>;
  if (view === 'home') return <div className="landing"><header className="site-header"><Brand/><nav><a href={CHANNEL} target="_blank" rel="noreferrer"><Youtube size={18}/> @supremegenz <ArrowUpRight size={16}/></a><span className="version">COMMUNITY EDITION / 01</span></nav></header><main>
    <div className="hero"><section className="hero-copy"><div className="eyebrow"><span className="live-dot"/> YOUR CREW. ZERO DISTANCE.</div><h1>Good people.<br/>Great conversations.<br/><em>Supreme energy.</em></h1><p>Your own space to link up, share a screen, and make things happen. Built for the Supreme GenZ community.</p><div className="hero-pills"><span><ShieldCheck size={16}/> Host-approved entry</span><span><Zap size={16}/> No app installation</span></div><div className="channel-card"><div className="channel-avatar">SG<span>↗</span></div><div><strong>THE SUPREME GENZ UNIVERSE</strong><p>One community. More ways to connect.</p></div><a href={CHANNEL} target="_blank" rel="noreferrer" aria-label="Visit Supreme GenZ YouTube channel"><ArrowUpRight/></a></div></section>
    <section className="launch-card"><div className="card-head"><Radio size={22}/><span>LET’S GET EVERYONE TOGETHER</span></div><h2>Make room for your people.</h2><form onSubmit={createMeeting}><label>Room name<input value={title} onChange={e => setTitle(e.target.value)} maxLength={80} required placeholder="Friday catch-up"/></label><div className="two-fields"><label>Your name<input value={name} onChange={e => setName(e.target.value)} maxLength={40} required placeholder="What should we call you?"/></label><label>Room password <span>optional</span><input type="password" value={password} onChange={e => setPassword(e.target.value)} maxLength={128} autoComplete="new-password" placeholder="Extra privacy"/></label></div>{config?.hostKeyRequired && <label>Host access key<input type="password" value={hostKey} onChange={e => setHostKey(e.target.value)} autoComplete="off" required placeholder="From your Render environment settings"/></label>}<button className="primary wide" disabled={busy || !config}><Plus size={19}/>{busy ? 'Creating your room…' : 'Start a meeting'}<ArrowUpRight size={19}/></button></form><div className="divider"><span>OR JOIN THE CONVERSATION</span></div><form className="join-form" onSubmit={openMeeting}><input aria-label="Meeting link or code" placeholder="Paste a meeting link or code" value={joinCode} onChange={e => setJoinCode(e.target.value)} required/><button className="join-button" aria-label="Join meeting"><ArrowRight size={21}/></button></form><p className="small-muted">Up to {config?.maxParticipants || 8} people · No meeting subscription</p></section></div>
    <section className="feature-strip"><div><MonitorUp/><strong>Show, don’t just tell.</strong><p>Share your screen, ideas, or next big thing.</p></div><div><MessageSquare/><strong>Keep the conversation going.</strong><p>Chat, reactions, notes, and a shared whiteboard.</p></div><div><ShieldCheck/><strong>Your room. Your rules.</strong><p>Waiting room, room lock, and co-host controls.</p></div></section>
    <div className="hosting-note"><span className="status-dot"/> FREE-SERVICE MODE <span>Temporary rooms. Download anything you want to keep before leaving. Server restarts clear meeting data.</span></div>
    </main><footer><span>SUPREME MEET <span className="muted">/ @supremegenz</span></span><span>Link up. Stay Supreme.</span></footer>{toastElement}</div>;

  if (view === 'prejoin' || view === 'waiting') return <div className="prejoin-page"><header className="site-header"><Brand/><a className="text-link" href={CHANNEL} target="_blank" rel="noreferrer">@supremegenz <ArrowUpRight size={16}/></a></header><main className="prejoin"><section><div className="preview"><video ref={previewRef} autoPlay playsInline muted className={!camera ? 'hidden-video' : 'mirror'}/>{!camera && <div className="preview-placeholder"><div className="avatar">{initials(name || 'SM')}</div><p>Your camera is off</p></div>}<div className="preview-controls">{meetingControls}</div></div><div className="row spaced"><button onClick={() => acquireMedia()}><Video size={16}/> Enable camera & mic</button><button onClick={() => acquireMedia(false,true)}><Mic size={16}/> Audio only</button></div><p className="muted">Preview is private until you’re admitted. Headphones help prevent echoes.</p></section><section className="prejoin-info"><div className="eyebrow">{view === 'waiting' ? 'HANG TIGHT' : 'YOU’RE ALMOST IN'}</div><h1>{room?.title || 'Join your people.'}</h1>{fatal ? <p className="error" role="alert">{fatal}</p> : view === 'waiting' ? <><div className="waiting-pulse"><Radio size={28}/></div><h2>Waiting for the host</h2><p className="muted">The host will let you in shortly. You can still adjust your camera and microphone.</p><button onClick={leave}>Cancel request</button></> : <><label>Your name<input value={name} onChange={e => setName(e.target.value)} maxLength={40} placeholder="Enter your name"/></label>{room?.passwordRequired && !storage.get(`host:${code}`) && <label>Meeting password<input type="password" value={password} onChange={e => setPassword(e.target.value)}/></label>}<button className="primary wide" onClick={join} disabled={busy || !room}>{busy ? 'Connecting…' : storage.get(`host:${code}`) ? 'Enter your room' : 'Ask to join'}<ArrowRight size={18}/></button><p className="muted">Joining shares your display name with the room. Recording requires everyone’s permission.</p>{config && !config.turnConfigured && <p className="notice">Direct-call mode: some work, school, or mobile networks need a TURN relay. Ask the host if calls don’t connect.</p>}</>}<a href="/" className="text-link">Back to home</a></section></main>{toastElement}</div>;

  if (view === 'ended') return <div className="end-page"><Brand/><div className="end-card"><div className="end-icon"><Check size={32}/></div><h1>Catch you next time.</h1><p>{fatal}</p><a className="primary" href="/">Back to Supreme Meet <ArrowRight size={18}/></a><a className="text-link" href={CHANNEL} target="_blank" rel="noreferrer">Keep the energy going on @supremegenz <ArrowUpRight size={16}/></a></div>{toastElement}</div>;

  const sorted = [...(meeting?.participants || [])].sort((a,b) => (b.id === pinned ? 2 : b.sharing ? 1 : 0) - (a.id === pinned ? 2 : a.sharing ? 1 : 0));
  return <div className="meeting-page"><header className="meeting-header"><Brand/><div className="meeting-title"><strong>{meeting?.title}</strong><span><span className="live-dot"/>{online ? 'LIVE ROOM' : 'RECONNECTING'}<span className="timer">{Math.floor(elapsed/60)}:{String(elapsed%60).padStart(2,'0')}</span></span></div><div className="row"><button className="invite-button" onClick={copyLink}><Copy size={16}/><span>Invite your crew</span></button><IconButton icon={light ? Moon : Sun} label="Toggle light theme" onClick={() => setLight(!light)}/></div></header>
    {!online && <div className="connection-banner" role="alert">Connection interrupted. Reconnecting automatically… If the server restarted, the host needs to create a new meeting.</div>}
    {meeting?.participants.some(p => p.recording) && <div className="recording-banner">● A participant is recording. Only continue if you consent; you can leave at any time.</div>}
    <div className="meeting-body"><main className="stage"><div className={`video-grid count-${sorted.length} ${pinned || sorted.some(p => p.sharing) ? 'focus-grid' : ''}`}>{sorted.map((p,i) => <VideoTile key={p.id} participant={p} camera={p.id === selfId ? local : remotes[p.id]?.camera} screen={p.id === selfId ? screen : remotes[p.id]?.screen} self={p.id === selfId} connection={connections[p.id]} pinned={i === 0 && !!(pinned || sorted.some(p => p.sharing))} onPin={() => setPinned(pinned === p.id ? '' : p.id)}/>)}</div>{sorted.length === 1 && <div className="alone-note"><Radio size={17}/><span>The room’s ready. Send the link and bring your people in.</span><button onClick={copyLink}>Copy invite</button></div>}<div className="stage-caption"><span><ShieldCheck size={14}/> Host-approved room · {code}</span><span>SUPREME ENERGY ONLY ↗</span></div></main>
    {panel && <aside className="side-panel"><div className="panel-heading"><h2>{{people:'The crew',chat:'Room chat',board:'Whiteboard',notes:'Shared notes',poll:'Quick poll',settings:'Room settings'}[panel]}</h2><IconButton icon={X} label="Close panel" onClick={() => setPanel('')}/></div><div className="panel-content">
    {panel === 'people' && <>{host && waiting.length > 0 && <section className="waiting-list"><h3>Waiting to join · {waiting.length}</h3>{waiting.map(p => <div className="waiting-person" key={p.id}><strong>{p.name}</strong><div className="row"><button onClick={() => action('admit',{id:p.id})}>Admit</button><button onClick={() => action('reject',{id:p.id})}>Decline</button></div></div>)}</section>}<div className="panel-section-label">IN THE ROOM · {sorted.length}</div>{meeting?.participants.map(p => <div className="person" key={p.id}><div className="person-summary"><span className="small-avatar">{initials(p.name)}</span><div><strong>{p.name}{p.id === selfId ? ' (you)' : ''}</strong><small>{p.role === 'guest' ? 'Participant' : p.role}</small></div>{p.hand && <span>✋</span>}{!p.mic && <MicOff size={15}/>}</div>{host && p.id !== selfId && p.role !== 'host' && (self.role === 'host' || p.role === 'guest') && <div className="person-actions"><button onClick={() => action('control',{id:p.id,action:'mute'})}>Mute</button><button onClick={() => action('control',{id:p.id,action:'request-unmute'})}>Ask to unmute</button>{self.role === 'host' && <button onClick={() => action('control',{id:p.id,action:p.role === 'cohost' ? 'guest' : 'cohost'})}>{p.role === 'cohost' ? 'Remove co-host' : 'Make co-host'}</button>}<button className="text-danger" onClick={() => confirm(`Remove ${p.name}?`) && action('control',{id:p.id,action:'remove'})}>Remove</button></div>}</div>)}{host && <button className="secondary wide" onClick={() => sorted.filter(p => p.id !== selfId && p.role === 'guest').forEach(p => action('control',{id:p.id,action:'mute'}))}>Mute participants</button>}<p className="muted">Participants may unmute themselves. Host controls cannot remotely activate a microphone or camera.</p></>}
    {panel === 'chat' && <><p className="notice">Chat is visible to everyone in this room and clears when the server restarts.</p><div className="messages">{messages.length === 0 && <div className="empty-panel"><MessageSquare/><p>First words? Make them Supreme.</p></div>}{messages.map(m => <div className="message" key={m.id}><div><strong>{m.name}</strong><time>{fmtTime(m.at)}</time></div><p>{m.text}</p></div>)}</div><form className="chat-form" onSubmit={e => { e.preventDefault(); send('chat',{text:message}).then(() => setMessage('')).catch(e => notify(e.message)); }}><input aria-label="Chat message" value={message} onChange={e => setMessage(e.target.value)} maxLength={2000} placeholder="Say something…" disabled={!meeting?.chatEnabled && !host}/><button aria-label="Send message" disabled={!message.trim()}><Send size={18}/></button></form><button className="text-button" onClick={() => download('supreme-chat.txt',messages.map(m => `[${fmtTime(m.at)}] ${m.name}: ${m.text}`).join('\n'))}><Download size={15}/> Download chat</button></>}
    {panel === 'board' && <Whiteboard strokes={board} host={host} notify={notify} onStroke={stroke => send('draw',stroke).then(() => setBoard(prev => [...prev,stroke])).catch(e => notify(e.message))} onClear={() => confirm('Clear the shared whiteboard for everyone?') && action('clear-board')}/>}
    {panel === 'notes' && <><p className="muted">Shared with everyone. Latest edit wins—take turns typing.</p><textarea className="notes" aria-label="Shared meeting notes" maxLength={12000} placeholder="Ideas, action items, things worth remembering…" value={notes} onChange={e => setNote(e.target.value)}/><button onClick={() => download('supreme-notes.txt',notes)}><Download size={16}/> Download notes</button></>}
    {panel === 'poll' && <>{poll ? <div className="poll"><h3>{poll.question}</h3>{poll.choices.map((choice,i) => <button className="poll-choice" key={i} disabled={poll.closed} onClick={() => action('poll-vote',{choice:i})}><span>{choice}</span><strong>{poll.counts[i]}</strong><span className="poll-bar" style={{width:`${poll.total ? poll.counts[i]/poll.total*100 : 0}%`}}/></button>)}<p className="muted">{poll.total} vote{poll.total === 1 ? '' : 's'} · {poll.closed ? 'Closed' : 'Vote again to change your choice'}</p>{host && !poll.closed && <button onClick={() => action('poll-close')}>Close poll</button>}</div> : <div className="empty-panel"><BarChart3/><p>No poll yet. The host can start one.</p></div>}{host && <form className="poll-form" onSubmit={e => { e.preventDefault(); action('poll-create',{question:pollQuestion,choices:pollChoices.split('\n')}); }}><h3>{poll ? 'Replace with a new poll' : 'Ask the room'}</h3><label>Question<input value={pollQuestion} onChange={e => setPollQuestion(e.target.value)} maxLength={180} required/></label><label>Choices (one per line, up to 6)<textarea value={pollChoices} onChange={e => setPollChoices(e.target.value)} required/></label><button className="primary">Launch poll</button></form>}</>}
    {panel === 'settings' && <><h3>Your devices</h3><label>Microphone<select value={audioDevice} onChange={e => setAudioDevice(e.target.value)}><option value="">System default</option>{devices.filter(d => d.kind === 'audioinput').map((d,i) => <option key={d.deviceId || i} value={d.deviceId}>{d.label || `Microphone ${i+1}`}</option>)}</select></label><label>Camera<select value={videoDevice} onChange={e => setVideoDevice(e.target.value)}><option value="">System default</option>{devices.filter(d => d.kind === 'videoinput').map((d,i) => <option key={d.deviceId || i} value={d.deviceId}>{d.label || `Camera ${i+1}`}</option>)}</select></label><button onClick={() => acquireMedia(true,true)}>Apply devices & enable media</button><p className="muted">Noise suppression and echo cancellation are requested automatically where supported. Speaker selection uses your device’s system settings.</p>{host && <><h3>Host controls</h3>{[['locked','Lock meeting'],['chatEnabled','Allow participant chat'],['shareEnabled','Allow participant screen sharing']].map(([key,label]) => <label className="toggle-row" key={key}>{label}<input type="checkbox" checked={meeting[key]} onChange={e => action('settings',{[key]:e.target.checked})}/></label>)}<button onClick={attendance}><Download size={16}/> Attendance CSV</button></>}<h3>Before you leave</h3><p className="muted">Rooms and meeting data are temporary. Save chat, notes, attendance, and whiteboards now. Local recording captures your chosen surface, not an automatic all-participant mix.</p></>}
    </div></aside>}
    </div><footer className="meeting-footer"><div className="footer-left"><span className="status-dot"/> {online ? 'Connected' : 'Reconnecting'}</div><div className="call-controls">{meetingControls}<span className="control-divider"/><IconButton icon={MonitorUp} label={screen ? 'Stop sharing' : 'Share screen'} active={!!screen} disabled={!host && !meeting?.shareEnabled} onClick={share}/><IconButton icon={Hand} label={hand ? 'Lower hand' : 'Raise hand'} active={hand} onClick={() => { setHand(!hand); action('media',{hand:!hand}); }}/><IconButton icon={recording ? Square : Circle} label={recording ? 'Stop recording' : 'Record locally'} active={recording} onClick={record}/><div className="reaction-wrap"><button aria-label="Send applause" title="Send applause" onClick={() => action('reaction',{emoji:'👏'})}>👏</button></div><IconButton icon={PhoneOff} label="Leave meeting" danger onClick={leave}/>{host && <button className="end-button" onClick={() => confirm('End this meeting for everyone? Download your reports first.') && action('end')}>End for all</button>}</div><div className="panel-controls">{[[Users,'people','Participants'],[MessageSquare,'chat','Chat'],[Pencil,'board','Whiteboard'],[NotebookPen,'notes','Notes'],[BarChart3,'poll','Polls'],[Settings,'settings','Settings']].map(([icon,key,label]) => <IconButton key={key} icon={icon} label={label} active={panel === key} onClick={() => setPanel(panel === key ? '' : key)}>{key === 'people' && waiting.length > 0 && host && <span className="badge">{waiting.length}</span>}</IconButton>)}<IconButton icon={Maximize} label="Fullscreen" onClick={() => { const task = document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen?.(); task?.catch(() => notify('Fullscreen is not available.')); }}/></div></footer>{toastElement}</div>;
}
createRoot(document.getElementById('root')).render(<App/>);
